server:
  port: 0
spring:
  datasource:
    url: jdbc:h2:mem:test-db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true

eureka:
  instance:
    instance-id: member-microservice-instance #Eureka가 인식할 instance ID
    appname: member-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka #Eureka Server가 위치하고 있는 기본 주소