server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8

eureka:
  instance:
    instance-id: gateway-microservice-instance #Eureka가 인식할 instance ID
    appname: gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka #Eureka Server가 위치하고 있는 기본 주소

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - name: LoggingFilter
          args:
            baseMessage: Spring Cloud Gateway LoggingFilter
            preLogger: true
            postLogger: true
      routes:
        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/members/**         # 해당 gateway 서버의 /account/** 요청은 account-service로 인식
        - id: test-service
          uri: lb://test-service
          predicates:
            - Path=/test/**